# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: instapet
    ports:
    - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080